"use client";

/**
 * Sound, synthesised. No audio files.
 *
 * Flying Sushi has music and effects, and SCOPE's reason for skipping them
 * ("no assets") was disproved by Zul's own repo. But shipping .mp3s would bring
 * back everything the art layer just escaped: licensing, weight in a Worker
 * bundle, and a fixed mood that cannot follow a spec.
 *
 * So every sound here is generated by the Web Audio API at runtime. The whole
 * soundtrack costs zero bytes of asset, works offline, and - because it is
 * numbers rather than a recording - a hard game can be given a darker key than
 * an easy one from the same code.
 *
 * Three rules this module obeys, all of them things browsers enforce:
 *
 * 1. **An AudioContext may only start from a user gesture.** Creating one at
 *    import time yields a suspended context that never plays, and the failure
 *    is silent. `unlock()` is called from the press that starts the game.
 * 2. **Nothing may throw into the game loop.** A blocked or missing audio stack
 *    must cost the player a sound, never a frame. Every entry point is guarded.
 * 3. **Mute is a preference, not a session flag.** It persists, because a
 *    student muting a game in a classroom means it every time.
 */

const STORAGE_KEY = "gamerator.muted";

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let muted = false;
let loaded = false;

/** Reads the persisted preference once. Safe where storage is unavailable. */
function loadPref() {
  if (loaded) return;
  loaded = true;
  try {
    muted = window.localStorage.getItem(STORAGE_KEY) === "1";
  } catch {
    muted = false;
  }
}

export function isMuted(): boolean {
  loadPref();
  return muted;
}

/**
 * Mute as an external store, for `useSyncExternalStore`.
 *
 * The preference genuinely lives here and in localStorage, not in React, so
 * mirroring it into component state with an effect would be keeping two copies
 * of one fact - which is what React's `set-state-in-effect` rule objects to,
 * correctly. The server snapshot is always false: localStorage does not exist
 * during a render on a Worker, and claiming to know the preference there would
 * be a hydration mismatch waiting for the first muted visitor.
 */
const listeners = new Set<() => void>();

export function subscribeMute(fn: () => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

export const mutedSnapshot = (): boolean => isMuted();
export const mutedServerSnapshot = (): boolean => false;

export function setMuted(next: boolean) {
  loadPref();
  muted = next;
  try {
    window.localStorage.setItem(STORAGE_KEY, next ? "1" : "0");
  } catch {
    // A browser with storage blocked still gets a working mute for this
    // session. Losing the preference is a smaller failure than throwing.
  }
  if (master && ctx) master.gain.setTargetAtTime(next ? 0 : 0.9, ctx.currentTime, 0.02);
  if (next) stopMusic();
  for (const fn of listeners) fn();
}

/**
 * Creates or resumes the audio context. MUST be called from a user gesture.
 * Returns null when audio is unavailable, and callers simply do nothing.
 */
export function unlock(): AudioContext | null {
  loadPref();
  try {
    if (!ctx) {
      const AC =
        window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext })
          .webkitAudioContext;
      if (!AC) return null;
      ctx = new AC();
      master = ctx.createGain();
      master.gain.value = muted ? 0 : 0.9;
      master.connect(ctx.destination);
    }
    if (ctx.state === "suspended") void ctx.resume();
    return ctx;
  } catch {
    return null;
  }
}

/**
 * One synthesised note: an oscillator through its own envelope.
 *
 * The envelope is the whole trick. A raw oscillator switched on and off clicks,
 * because the waveform jumps from silence mid-cycle; ramping the gain in and
 * out is what turns a beep into something that sounds intended.
 */
function note(
  freq: number,
  {
    at = 0,
    dur = 0.12,
    type = "square" as OscillatorType,
    gain = 0.2,
    slideTo = 0,
  } = {},
) {
  if (!ctx || !master || muted) return;
  const t0 = ctx.currentTime + at;
  const osc = ctx.createOscillator();
  const env = ctx.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, t0);
  if (slideTo) osc.frequency.exponentialRampToValueAtTime(Math.max(20, slideTo), t0 + dur);
  env.gain.setValueAtTime(0.0001, t0);
  env.gain.exponentialRampToValueAtTime(gain, t0 + 0.008);
  env.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);
  osc.connect(env);
  env.connect(master);
  osc.start(t0);
  osc.stop(t0 + dur + 0.02);
}

/** Filtered noise, for impacts. A square wave cannot sound like a thud. */
function noise(dur = 0.18, gain = 0.25) {
  if (!ctx || !master || muted) return;
  const n = Math.floor(ctx.sampleRate * dur);
  const buf = ctx.createBuffer(1, n, ctx.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < n; i++) data[i] = (Math.random() * 2 - 1) * (1 - i / n) ** 2;
  const src = ctx.createBufferSource();
  src.buffer = buf;
  const lp = ctx.createBiquadFilter();
  lp.type = "lowpass";
  lp.frequency.value = 900;
  const env = ctx.createGain();
  env.gain.value = gain;
  src.connect(lp);
  lp.connect(env);
  env.connect(master);
  src.start();
}

export type Sfx = "flap" | "score" | "coin" | "hit" | "die" | "win" | "start" | "power";

/**
 * `combo` rises with the score so consecutive points climb a scale instead of
 * repeating one tone. It is the cheapest possible reward signal and it is why
 * a long run sounds like progress.
 */
export function play(name: Sfx, combo = 0) {
  if (!ctx || muted) return;
  try {
    switch (name) {
      case "flap":
        note(520, { dur: 0.07, type: "triangle", gain: 0.14, slideTo: 700 });
        break;
      case "score": {
        const step = [0, 2, 4, 7, 9, 12][combo % 6];
        note(440 * 2 ** (step / 12), { dur: 0.1, type: "square", gain: 0.13 });
        break;
      }
      case "coin":
        note(988, { dur: 0.06, type: "square", gain: 0.14 });
        note(1319, { at: 0.06, dur: 0.11, type: "square", gain: 0.14 });
        break;
      case "power":
        // Deliberately unlike a coin: a rising four-note run, so a power-up is
        // audibly a different KIND of thing rather than a bigger coin. 1568 is
        // unique to it, which is also what makes pickups countable in a probe.
        [784, 1047, 1319, 1568].forEach((f, i) =>
          note(f, { at: i * 0.05, dur: 0.14, type: "triangle", gain: 0.15 }),
        );
        break;
      case "hit":
        noise(0.16, 0.3);
        note(180, { dur: 0.16, type: "sawtooth", gain: 0.16, slideTo: 70 });
        break;
      case "die":
        noise(0.22, 0.28);
        [523, 415, 330, 247].forEach((f, i) =>
          note(f, { at: i * 0.11, dur: 0.16, type: "triangle", gain: 0.17 }),
        );
        break;
      case "win":
        [523, 659, 784, 1047].forEach((f, i) =>
          note(f, { at: i * 0.1, dur: 0.22, type: "square", gain: 0.16 }),
        );
        break;
      case "start":
        note(523, { dur: 0.09, type: "square", gain: 0.15 });
        note(784, { at: 0.09, dur: 0.14, type: "square", gain: 0.15 });
        break;
    }
  } catch {
    // Never let a sound break a frame.
  }
}

/* ------------------------------------------------------------------ music */

/**
 * A looping bass-and-arpeggio bed, scheduled ahead of time.
 *
 * Notes are queued against the audio clock rather than fired from a timer,
 * because `setInterval` drifts by tens of milliseconds under load and the game
 * loop is already competing for the main thread. The timer only decides WHEN TO
 * QUEUE; the audio clock decides when a note sounds, so the tempo holds steady
 * even when a frame is late.
 */
const PROGRESSION = [
  [0, 4, 7, 11],
  [-3, 2, 5, 9],
  [-5, 0, 4, 7],
  [2, 5, 9, 12],
];

let timer: number | null = null;
let beat = 0;
let nextAt = 0;
let root = 220;

export function startMusic(dark = false) {
  if (!ctx || muted || timer !== null) return;
  root = dark ? 165 : 220;
  beat = 0;
  nextAt = ctx.currentTime + 0.1;
  const tick = () => {
    if (!ctx) return;
    // Queue every note that falls inside the next 200ms.
    while (nextAt < ctx.currentTime + 0.2) {
      const bar = PROGRESSION[Math.floor(beat / 8) % PROGRESSION.length];
      const semi = bar[beat % 4];
      const at = nextAt - ctx.currentTime;
      if (beat % 4 === 0) note(root / 2, { at, dur: 0.3, type: "triangle", gain: 0.1 });
      note(root * 2 ** (semi / 12), {
        at,
        dur: 0.14,
        type: "square",
        gain: beat % 2 === 0 ? 0.055 : 0.035,
      });
      beat += 1;
      nextAt += 0.15;
    }
  };
  tick();
  timer = window.setInterval(tick, 60);
}

export function stopMusic() {
  if (timer !== null) {
    window.clearInterval(timer);
    timer = null;
  }
}
