/* GENERATED - do not hand-edit.
 * Source: Pandai Design System 1.5 (Figma TLVKe3bgJTdVvuPAzgDq2f)
 * Extracted: 2026-09-06
 * Modes: Semantic=Light, Product=Student, Primitives=Value
 * Regenerate: node scripts/generate-tokens.mjs
 * Re-fetch from Figma: scripts/sync-tokens.md
 */

/** Every DS token path that exists in this build, mapped to its CSS variable. */
export const TOKEN_VARS = {
  "Accents/Azure/default": "--accents-azure-default",
  "Accents/Azure/default-hover": "--accents-azure-default-hover",
  "Accents/Azure/focus": "--accents-azure-focus",
  "Accents/Azure/on-color": "--accents-azure-on-color",
  "Accents/Azure/on-color-hover": "--accents-azure-on-color-hover",
  "Accents/Butter/default": "--accents-butter-default",
  "Accents/Butter/default-hover": "--accents-butter-default-hover",
  "Accents/Butter/focus": "--accents-butter-focus",
  "Accents/Butter/on-color": "--accents-butter-on-color",
  "Accents/Butter/on-color-hover": "--accents-butter-on-color-hover",
  "Accents/Minion/default": "--accents-minion-default",
  "Accents/Minion/default-hover": "--accents-minion-default-hover",
  "Accents/Minion/focus": "--accents-minion-focus",
  "Accents/Minion/on-color": "--accents-minion-on-color",
  "Accents/Minion/on-color-hover": "--accents-minion-on-color-hover",
  "Accents/Pumpkin/default": "--accents-pumpkin-default",
  "Accents/Pumpkin/default-hover": "--accents-pumpkin-default-hover",
  "Accents/Pumpkin/focus": "--accents-pumpkin-focus",
  "Accents/Pumpkin/on-color": "--accents-pumpkin-on-color",
  "Accents/Pumpkin/on-color-hover": "--accents-pumpkin-on-color-hover",
  "Border/alert/default": "--border-alert-default",
  "Border/alert/default-hover": "--border-alert-default-hover",
  "Border/alert/default-subtle": "--border-alert-default-subtle",
  "Border/alert/default-subtle-hover": "--border-alert-default-subtle-hover",
  "Border/alert/focus": "--border-alert-focus",
  "Border/bronze/default": "--border-bronze-default",
  "Border/bronze/default-hover": "--border-bronze-default-hover",
  "Border/bronze/default-subtle": "--border-bronze-default-subtle",
  "Border/bronze/default-subtle-hover": "--border-bronze-default-subtle-hover",
  "Border/bronze/focus": "--border-bronze-focus",
  "Border/default": "--border-default",
  "Border/disabled/primary": "--border-disabled-primary",
  "Border/disabled/secondary": "--border-disabled-secondary",
  "Border/general/default": "--border-general-default",
  "Border/general/default-secondary": "--border-general-default-secondary",
  "Border/general/default-tertiary": "--border-general-default-tertiary",
  "Border/general/page": "--border-general-page",
  "Border/general/page-secondary": "--border-general-page-secondary",
  "Border/gold/default": "--border-gold-default",
  "Border/gold/default-hover": "--border-gold-default-hover",
  "Border/gold/default-subtle": "--border-gold-default-subtle",
  "Border/gold/default-subtle-hover": "--border-gold-default-subtle-hover",
  "Border/gold/focus": "--border-gold-focus",
  "Border/informative/default": "--border-informative-default",
  "Border/informative/default-hover": "--border-informative-default-hover",
  "Border/informative/default-subtle": "--border-informative-default-subtle",
  "Border/informative/default-subtle-hover": "--border-informative-default-subtle-hover",
  "Border/informative/focus": "--border-informative-focus",
  "Border/on-color": "--border-on-color",
  "Border/primary/default": "--border-primary-default",
  "Border/primary/default-hover": "--border-primary-default-hover",
  "Border/primary/default-subtle": "--border-primary-default-subtle",
  "Border/primary/default-subtle-hover": "--border-primary-default-subtle-hover",
  "Border/primary/focus": "--border-primary-focus",
  "Border/secondary/default": "--border-secondary-default",
  "Border/secondary/default-hover": "--border-secondary-default-hover",
  "Border/secondary/default-subtle": "--border-secondary-default-subtle",
  "Border/secondary/default-subtle-hover": "--border-secondary-default-subtle-hover",
  "Border/secondary/focus": "--border-secondary-focus",
  "Border/silver/default": "--border-silver-default",
  "Border/silver/default-hover": "--border-silver-default-hover",
  "Border/silver/default-subtle": "--border-silver-default-subtle",
  "Border/silver/default-subtle-hover": "--border-silver-default-subtle-hover",
  "Border/silver/focus": "--border-silver-focus",
  "Border/success/default": "--border-success-default",
  "Border/success/default-hover": "--border-success-default-hover",
  "Border/success/default-subtle": "--border-success-default-subtle",
  "Border/success/default-subtle-hover": "--border-success-default-subtle-hover",
  "Border/success/focus": "--border-success-focus",
  "Border/tertiary/default": "--border-tertiary-default",
  "Border/tertiary/default-hover": "--border-tertiary-default-hover",
  "Border/tertiary/default-subtle": "--border-tertiary-default-subtle",
  "Border/tertiary/default-subtle-hover": "--border-tertiary-default-subtle-hover",
  "Border/tertiary/focus": "--border-tertiary-focus",
  "Border/warning/default": "--border-warning-default",
  "Border/warning/default-hover": "--border-warning-default-hover",
  "Border/warning/default-subtle": "--border-warning-default-subtle",
  "Border/warning/default-subtle-hover": "--border-warning-default-subtle-hover",
  "Border/warning/focus": "--border-warning-focus",
  "Border Width/lg": "--border-width-lg",
  "Border Width/m": "--border-width-m",
  "Border Width/none": "--border-width-none",
  "Border Width/s": "--border-width-s",
  "Border Width/xs": "--border-width-xs",
  "Icon/alert/default": "--icon-alert-default",
  "Icon/alert/default-hover": "--icon-alert-default-hover",
  "Icon/alert/focus": "--icon-alert-focus",
  "Icon/alert/on-color": "--icon-alert-on-color",
  "Icon/alert/on-color-hover": "--icon-alert-on-color-hover",
  "Icon/default/default": "--icon-default-default",
  "Icon/disabled/default": "--icon-disabled-default",
  "Icon/disabled/on-color": "--icon-disabled-on-color",
  "Icon/disabled/on-icon": "--icon-disabled-on-icon",
  "Icon/grayscale/ramp-1": "--icon-grayscale-ramp-1",
  "Icon/grayscale/ramp-2": "--icon-grayscale-ramp-2",
  "Icon/grayscale/ramp-3": "--icon-grayscale-ramp-3",
  "Icon/grayscale/ramp-4": "--icon-grayscale-ramp-4",
  "Icon/grayscale/ramp-5": "--icon-grayscale-ramp-5",
  "Icon/informative/default": "--icon-informative-default",
  "Icon/informative/default-hover": "--icon-informative-default-hover",
  "Icon/informative/focus": "--icon-informative-focus",
  "Icon/informative/on-color": "--icon-informative-on-color",
  "Icon/informative/on-color-hover": "--icon-informative-on-color-hover",
  "Icon/primary/default": "--icon-primary-default",
  "Icon/primary/default-hover": "--icon-primary-default-hover",
  "Icon/primary/focus": "--icon-primary-focus",
  "Icon/primary/on-color": "--icon-primary-on-color",
  "Icon/primary/on-color-hover": "--icon-primary-on-color-hover",
  "Icon/secondary/default": "--icon-secondary-default",
  "Icon/secondary/default-hover": "--icon-secondary-default-hover",
  "Icon/secondary/focus": "--icon-secondary-focus",
  "Icon/secondary/on-color": "--icon-secondary-on-color",
  "Icon/secondary/on-color-hover": "--icon-secondary-on-color-hover",
  "Icon/success/default": "--icon-success-default",
  "Icon/success/default-hover": "--icon-success-default-hover",
  "Icon/success/focus": "--icon-success-focus",
  "Icon/success/on-color": "--icon-success-on-color",
  "Icon/success/on-color-hover": "--icon-success-on-color-hover",
  "Icon/tertiary/default": "--icon-tertiary-default",
  "Icon/tertiary/default-hover": "--icon-tertiary-default-hover",
  "Icon/tertiary/focus": "--icon-tertiary-focus",
  "Icon/tertiary/on-color": "--icon-tertiary-on-color",
  "Icon/tertiary/on-color-hover": "--icon-tertiary-on-color-hover",
  "Icon/warning/default": "--icon-warning-default",
  "Icon/warning/default-hover": "--icon-warning-default-hover",
  "Icon/warning/focus": "--icon-warning-focus",
  "Icon/warning/on-color": "--icon-warning-on-color",
  "Icon/warning/on-color-hover": "--icon-warning-on-color-hover",
  "Radius/2xl": "--radius-2xl",
  "Radius/3xl": "--radius-3xl",
  "Radius/4xl": "--radius-4xl",
  "Radius/full": "--radius-full",
  "Radius/lg": "--radius-lg",
  "Radius/md": "--radius-md",
  "Radius/none": "--radius-none",
  "Radius/pill": "--radius-pill",
  "Radius/sm": "--radius-sm",
  "Radius/xl": "--radius-xl",
  "Radius/xs": "--radius-xs",
  "Spacing/component/2xl": "--spacing-component-2xl",
  "Spacing/component/2xs": "--spacing-component-2xs",
  "Spacing/component/3xl": "--spacing-component-3xl",
  "Spacing/component/3xs": "--spacing-component-3xs",
  "Spacing/component/lg": "--spacing-component-lg",
  "Spacing/component/md": "--spacing-component-md",
  "Spacing/component/none": "--spacing-component-none",
  "Spacing/component/sm": "--spacing-component-sm",
  "Spacing/component/xl": "--spacing-component-xl",
  "Spacing/component/xs": "--spacing-component-xs",
  "Spacing/layout/lg": "--spacing-layout-lg",
  "Spacing/layout/md": "--spacing-layout-md",
  "Spacing/layout/sm": "--spacing-layout-sm",
  "Spacing/layout/xl": "--spacing-layout-xl",
  "Status/coins/default": "--status-coins-default",
  "Status/coins/focus": "--status-coins-focus",
  "Status/coins/on color": "--status-coins-on-color",
  "Status/lives/default": "--status-lives-default",
  "Status/lives/focus": "--status-lives-focus",
  "Status/lives/on color": "--status-lives-on-color",
  "Status/ruby/default": "--status-ruby-default",
  "Status/ruby/focus": "--status-ruby-focus",
  "Status/ruby/on color": "--status-ruby-on-color",
  "Status/score/default": "--status-score-default",
  "Status/score/focus": "--status-score-focus",
  "Status/score/on color": "--status-score-on-color",
  "Status/streak/default": "--status-streak-default",
  "Status/streak/focus": "--status-streak-focus",
  "Status/streak/on color": "--status-streak-on-color",
  "Subjects/account/default": "--subjects-account-default",
  "Subjects/account/default-hover": "--subjects-account-default-hover",
  "Subjects/account/default-subtle": "--subjects-account-default-subtle",
  "Subjects/account/default-subtle-hover": "--subjects-account-default-subtle-hover",
  "Subjects/account/focus": "--subjects-account-focus",
  "Subjects/add-math/default": "--subjects-add-math-default",
  "Subjects/add-math/default-hover": "--subjects-add-math-default-hover",
  "Subjects/add-math/default-subtle": "--subjects-add-math-default-subtle",
  "Subjects/add-math/default-subtle-hover": "--subjects-add-math-default-subtle-hover",
  "Subjects/add-math/focus": "--subjects-add-math-focus",
  "Subjects/b-melayu/default": "--subjects-b-melayu-default",
  "Subjects/b-melayu/default-hover": "--subjects-b-melayu-default-hover",
  "Subjects/b-melayu/default-subtle": "--subjects-b-melayu-default-subtle",
  "Subjects/b-melayu/default-subtle-hover": "--subjects-b-melayu-default-subtle-hover",
  "Subjects/b-melayu/focus": "--subjects-b-melayu-focus",
  "Subjects/biology/default": "--subjects-biology-default",
  "Subjects/biology/default-hover": "--subjects-biology-default-hover",
  "Subjects/biology/default-subtle": "--subjects-biology-default-subtle",
  "Subjects/biology/default-subtle-hover": "--subjects-biology-default-subtle-hover",
  "Subjects/biology/focus": "--subjects-biology-focus",
  "Subjects/business/default": "--subjects-business-default",
  "Subjects/business/default-hover": "--subjects-business-default-hover",
  "Subjects/business/default-subtle": "--subjects-business-default-subtle",
  "Subjects/business/default-subtle-hover": "--subjects-business-default-subtle-hover",
  "Subjects/business/focus": "--subjects-business-focus",
  "Subjects/chemistry/default": "--subjects-chemistry-default",
  "Subjects/chemistry/default-hover": "--subjects-chemistry-default-hover",
  "Subjects/chemistry/default-subtle": "--subjects-chemistry-default-subtle",
  "Subjects/chemistry/default-subtle-hover": "--subjects-chemistry-default-subtle-hover",
  "Subjects/chemistry/focus": "--subjects-chemistry-focus",
  "Subjects/chi-lang/default": "--subjects-chi-lang-default",
  "Subjects/chi-lang/default-hover": "--subjects-chi-lang-default-hover",
  "Subjects/chi-lang/default-subtle": "--subjects-chi-lang-default-subtle",
  "Subjects/chi-lang/default-subtle-hover": "--subjects-chi-lang-default-subtle-hover",
  "Subjects/chi-lang/focus": "--subjects-chi-lang-focus",
  "Subjects/comp-science/default": "--subjects-comp-science-default",
  "Subjects/comp-science/default-hover": "--subjects-comp-science-default-hover",
  "Subjects/comp-science/default-subtle": "--subjects-comp-science-default-subtle",
  "Subjects/comp-science/default-subtle-hover": "--subjects-comp-science-default-subtle-hover",
  "Subjects/comp-science/focus": "--subjects-comp-science-focus",
  "Subjects/economy/default": "--subjects-economy-default",
  "Subjects/economy/default-hover": "--subjects-economy-default-hover",
  "Subjects/economy/default-subtle": "--subjects-economy-default-subtle",
  "Subjects/economy/default-subtle-hover": "--subjects-economy-default-subtle-hover",
  "Subjects/economy/focus": "--subjects-economy-focus",
  "Subjects/english/default": "--subjects-english-default",
  "Subjects/english/default-hover": "--subjects-english-default-hover",
  "Subjects/english/default-subtle": "--subjects-english-default-subtle",
  "Subjects/english/default-subtle-hover": "--subjects-english-default-subtle-hover",
  "Subjects/english/focus": "--subjects-english-focus",
  "Subjects/geo/default": "--subjects-geo-default",
  "Subjects/geo/default-hover": "--subjects-geo-default-hover",
  "Subjects/geo/default-subtle": "--subjects-geo-default-subtle",
  "Subjects/geo/default-subtle-hover": "--subjects-geo-default-subtle-hover",
  "Subjects/geo/focus": "--subjects-geo-focus",
  "Subjects/history/default": "--subjects-history-default",
  "Subjects/history/default-hover": "--subjects-history-default-hover",
  "Subjects/history/default-subtle": "--subjects-history-default-subtle",
  "Subjects/history/default-subtle-hover": "--subjects-history-default-subtle-hover",
  "Subjects/history/focus": "--subjects-history-focus",
  "Subjects/islamic/default": "--subjects-islamic-default",
  "Subjects/islamic/default-hover": "--subjects-islamic-default-hover",
  "Subjects/islamic/default-subtle": "--subjects-islamic-default-subtle",
  "Subjects/islamic/default-subtle-hover": "--subjects-islamic-default-subtle-hover",
  "Subjects/islamic/focus": "--subjects-islamic-focus",
  "Subjects/kafa/default": "--subjects-kafa-default",
  "Subjects/kafa/default-hover": "--subjects-kafa-default-hover",
  "Subjects/kafa/default-subtle": "--subjects-kafa-default-subtle",
  "Subjects/kafa/default-subtle-hover": "--subjects-kafa-default-subtle-hover",
  "Subjects/kafa/focus": "--subjects-kafa-focus",
  "Subjects/math/default": "--subjects-math-default",
  "Subjects/math/default-hover": "--subjects-math-default-hover",
  "Subjects/math/default-subtle": "--subjects-math-default-subtle",
  "Subjects/math/default-subtle-hover": "--subjects-math-default-subtle-hover",
  "Subjects/math/focus": "--subjects-math-focus",
  "Subjects/moral/default": "--subjects-moral-default",
  "Subjects/moral/default-hover": "--subjects-moral-default-hover",
  "Subjects/moral/default-subtle": "--subjects-moral-default-subtle",
  "Subjects/moral/default-subtle-hover": "--subjects-moral-default-subtle-hover",
  "Subjects/moral/focus": "--subjects-moral-focus",
  "Subjects/physics/default": "--subjects-physics-default",
  "Subjects/physics/default-hover": "--subjects-physics-default-hover",
  "Subjects/physics/default-subtle": "--subjects-physics-default-subtle",
  "Subjects/physics/default-subtle-hover": "--subjects-physics-default-subtle-hover",
  "Subjects/physics/focus": "--subjects-physics-focus",
  "Subjects/rbt/default": "--subjects-rbt-default",
  "Subjects/rbt/default-hover": "--subjects-rbt-default-hover",
  "Subjects/rbt/default-subtle": "--subjects-rbt-default-subtle",
  "Subjects/rbt/default-subtle-hover": "--subjects-rbt-default-subtle-hover",
  "Subjects/rbt/focus": "--subjects-rbt-focus",
  "Subjects/science/default": "--subjects-science-default",
  "Subjects/science/default-hover": "--subjects-science-default-hover",
  "Subjects/science/default-subtle": "--subjects-science-default-subtle",
  "Subjects/science/default-subtle-hover": "--subjects-science-default-subtle-hover",
  "Subjects/science/focus": "--subjects-science-focus",
  "Surface/alert/default": "--surface-alert-default",
  "Surface/alert/default-hover": "--surface-alert-default-hover",
  "Surface/alert/default-subtle": "--surface-alert-default-subtle",
  "Surface/alert/default-subtle-hover": "--surface-alert-default-subtle-hover",
  "Surface/alert/focus": "--surface-alert-focus",
  "Surface/bronze/default": "--surface-bronze-default",
  "Surface/bronze/default-hover": "--surface-bronze-default-hover",
  "Surface/bronze/default-subtle": "--surface-bronze-default-subtle",
  "Surface/bronze/default-subtle-hover": "--surface-bronze-default-subtle-hover",
  "Surface/bronze/focus": "--surface-bronze-focus",
  "Surface/disabled/on color": "--surface-disabled-on-color",
  "Surface/disabled/primary": "--surface-disabled-primary",
  "Surface/disabled/secondary": "--surface-disabled-secondary",
  "Surface/general/default": "--surface-general-default",
  "Surface/general/default-alpha": "--surface-general-default-alpha",
  "Surface/general/default-secondary": "--surface-general-default-secondary",
  "Surface/general/default-tertiary": "--surface-general-default-tertiary",
  "Surface/general/page": "--surface-general-page",
  "Surface/general/page-secondary": "--surface-general-page-secondary",
  "Surface/general/pandai-logo": "--surface-general-pandai-logo",
  "Surface/gold/default": "--surface-gold-default",
  "Surface/gold/default-hover": "--surface-gold-default-hover",
  "Surface/gold/default-subtle": "--surface-gold-default-subtle",
  "Surface/gold/default-subtle-hover": "--surface-gold-default-subtle-hover",
  "Surface/gold/focus": "--surface-gold-focus",
  "Surface/informative/default": "--surface-informative-default",
  "Surface/informative/default-hover": "--surface-informative-default-hover",
  "Surface/informative/default-subtle": "--surface-informative-default-subtle",
  "Surface/informative/default-subtle-hover": "--surface-informative-default-subtle-hover",
  "Surface/informative/focus": "--surface-informative-focus",
  "Surface/menu-item/hover": "--surface-menu-item-hover",
  "Surface/primary/default": "--surface-primary-default",
  "Surface/primary/default-hover": "--surface-primary-default-hover",
  "Surface/primary/default-subtle": "--surface-primary-default-subtle",
  "Surface/primary/default-subtle-hover": "--surface-primary-default-subtle-hover",
  "Surface/primary/focus": "--surface-primary-focus",
  "Surface/secondary/default": "--surface-secondary-default",
  "Surface/secondary/default-btn": "--surface-secondary-default-btn",
  "Surface/secondary/default-hover": "--surface-secondary-default-hover",
  "Surface/secondary/default-subtle": "--surface-secondary-default-subtle",
  "Surface/secondary/default-subtle-hover": "--surface-secondary-default-subtle-hover",
  "Surface/secondary/focus": "--surface-secondary-focus",
  "Surface/silver/default": "--surface-silver-default",
  "Surface/silver/default-hover": "--surface-silver-default-hover",
  "Surface/silver/default-subtle": "--surface-silver-default-subtle",
  "Surface/silver/default-subtle-hover": "--surface-silver-default-subtle-hover",
  "Surface/silver/focus": "--surface-silver-focus",
  "Surface/success/default": "--surface-success-default",
  "Surface/success/default-hover": "--surface-success-default-hover",
  "Surface/success/default-subtle": "--surface-success-default-subtle",
  "Surface/success/default-subtle-hover": "--surface-success-default-subtle-hover",
  "Surface/success/focus": "--surface-success-focus",
  "Surface/tertiary/default": "--surface-tertiary-default",
  "Surface/tertiary/default-hover": "--surface-tertiary-default-hover",
  "Surface/tertiary/default-subtle": "--surface-tertiary-default-subtle",
  "Surface/tertiary/default-subtle-hover": "--surface-tertiary-default-subtle-hover",
  "Surface/tertiary/focus": "--surface-tertiary-focus",
  "Surface/warning/default": "--surface-warning-default",
  "Surface/warning/default-hover": "--surface-warning-default-hover",
  "Surface/warning/default-subtle": "--surface-warning-default-subtle",
  "Surface/warning/default-subtle-hover": "--surface-warning-default-subtle-hover",
  "Surface/warning/focus": "--surface-warning-focus",
  "Text/alert/default": "--text-alert-default",
  "Text/alert/default-hover": "--text-alert-default-hover",
  "Text/alert/on-color": "--text-alert-on-color",
  "Text/alert/on-color-hover": "--text-alert-on-color-hover",
  "Text/default/body": "--text-default-body",
  "Text/default/caption": "--text-default-caption",
  "Text/default/heading": "--text-default-heading",
  "Text/default/placeholder": "--text-default-placeholder",
  "Text/disabled/default": "--text-disabled-default",
  "Text/disabled/on-color": "--text-disabled-on-color",
  "Text/informative/default": "--text-informative-default",
  "Text/informative/default-hover": "--text-informative-default-hover",
  "Text/informative/on-color": "--text-informative-on-color",
  "Text/informative/on-color-hover": "--text-informative-on-color-hover",
  "Text/on-color/body": "--text-on-color-body",
  "Text/on-color/caption": "--text-on-color-caption",
  "Text/on-color/heading": "--text-on-color-heading",
  "Text/on-color/placeholder": "--text-on-color-placeholder",
  "Text/primary/default": "--text-primary-default",
  "Text/primary/default-hover": "--text-primary-default-hover",
  "Text/primary/focus": "--text-primary-focus",
  "Text/primary/on-color": "--text-primary-on-color",
  "Text/primary/on-color-hover": "--text-primary-on-color-hover",
  "Text/secondary/default": "--text-secondary-default",
  "Text/secondary/default-hover": "--text-secondary-default-hover",
  "Text/secondary/focus": "--text-secondary-focus",
  "Text/secondary/on-color": "--text-secondary-on-color",
  "Text/secondary/on-color-hover": "--text-secondary-on-color-hover",
  "Text/success/default": "--text-success-default",
  "Text/success/default-hover": "--text-success-default-hover",
  "Text/success/on-color": "--text-success-on-color",
  "Text/success/on-color-hover": "--text-success-on-color-hover",
  "Text/tertiary/default": "--text-tertiary-default",
  "Text/tertiary/default-hover": "--text-tertiary-default-hover",
  "Text/tertiary/focus": "--text-tertiary-focus",
  "Text/tertiary/on-color": "--text-tertiary-on-color",
  "Text/tertiary/on-color-hover": "--text-tertiary-on-color-hover",
  "Text/warning/default": "--text-warning-default",
  "Text/warning/default-hover": "--text-warning-default-hover",
  "Text/warning/on-color": "--text-warning-on-color",
  "Text/warning/on-color-hover": "--text-warning-on-color-hover",
} as const;

export type TokenPath = keyof typeof TOKEN_VARS;

/** `var(--surface-primary-default)`, typo-proof. */
export function token(path: TokenPath): string {
  return `var(${TOKEN_VARS[path]})`;
}

/**
 * Subject identities from the DS. A game's accent is DERIVED from its subject
 * rather than chosen, so a Bahasa Melayu game wears the same blue it wears
 * everywhere else in Pandai - and the model never has to guess a colour.
 */
export const SUBJECT_KEYS = [
  "account",
  "add-math",
  "b-melayu",
  "biology",
  "business",
  "chemistry",
  "chi-lang",
  "comp-science",
  "economy",
  "english",
  "geo",
  "history",
  "islamic",
  "kafa",
  "math",
  "moral",
  "physics",
  "rbt",
  "science",
] as const;

export type SubjectKey = (typeof SUBJECT_KEYS)[number];

/**
 * Semantic accent families carrying the complete Surface ramp. Used only where
 * a game has no subject to derive from.
 */
export const ACCENT_FAMILIES = [
  "alert",
  "bronze",
  "gold",
  "informative",
  "primary",
  "secondary",
  "silver",
  "success",
  "tertiary",
  "warning",
] as const;

export type AccentFamily = (typeof ACCENT_FAMILIES)[number];

/** Game status colours - the DS already ships these. */
export const STATUS_KEYS = [
  "coins",
  "lives",
  "ruby",
  "score",
  "streak",
] as const;

export type StatusKey = (typeof STATUS_KEYS)[number];

export type Ramp = {
  default: string;
  hover: string;
  subtle: string;
  subtleHover: string;
  focus: string;
};

const ramp = (prefix: string): Ramp => ({
  default: `var(--${prefix}-default)`,
  hover: `var(--${prefix}-default-hover)`,
  subtle: `var(--${prefix}-default-subtle)`,
  subtleHover: `var(--${prefix}-default-subtle-hover)`,
  focus: `var(--${prefix}-focus)`,
});

export const subjectRamp = (s: SubjectKey): Ramp => ramp(`subjects-${s}`);
export const accentRamp = (a: AccentFamily): Ramp => ramp(`surface-${a}`);

/** Spacing scale. The house rule is 16 - see docs/DESIGN-SYSTEM-SYNC.md. */
export const SPACING = {
  "none": 0,
  "3xs": 2,
  "2xs": 4,
  "xs": 8,
  "sm": 12,
  "md": 16,
  "lg": 20,
  "xl": 24,
  "2xl": 28,
  "3xl": 60,
} as const;

export const RADIUS = {
  "none": 0,
  "xs": 2,
  "sm": 4,
  "md": 8,
  "lg": 12,
  "xl": 16,
  "2xl": 18,
  "3xl": 24,
  "4xl": 54,
  "full": 60,
  "pill": 999,
} as const;
