/* GENERATED - do not hand-edit.
 * Source: Pandai Design System 1.5 (Figma TLVKe3bgJTdVvuPAzgDq2f)
 * Extracted: 2026-09-06
 * Modes: Semantic=Light, Product=Student, Primitives=Value
 * Regenerate: node scripts/generate-tokens.mjs
 * Re-fetch from Figma: scripts/sync-tokens.md
 */

/** Every DS token path that exists in this build, mapped to its CSS variable. */
export const TOKEN_VARS = {
  "Accents/Azure/default": "--accents-azure-default",
  "Accents/Azure/default-hover": "--accents-azure-default-hover",
  "Accents/Azure/focus": "--accents-azure-focus",
  "Accents/Azure/on-color": "--accents-azure-on-color",
  "Accents/Azure/on-color-hover": "--accents-azure-on-color-hover",
  "Accents/Butter/default": "--accents-butter-default",
  "Accents/Butter/default-hover": "--accents-butter-default-hover",
  "Accents/Butter/focus": "--accents-butter-focus",
  "Accents/Butter/on-color": "--accents-butter-on-color",
  "Accents/Butter/on-color-hover": "--accents-butter-on-color-hover",
  "Accents/Minion/default": "--accents-minion-default",
  "Accents/Minion/default-hover": "--accents-minion-default-hover",
  "Accents/Minion/focus": "--accents-minion-focus",
  "Accents/Minion/on-color": "--accents-minion-on-color",
  "Accents/Minion/on-color-hover": "--accents-minion-on-color-hover",
  "Accents/Pumpkin/default": "--accents-pumpkin-default",
  "Accents/Pumpkin/default-hover": "--accents-pumpkin-default-hover",
  "Accents/Pumpkin/focus": "--accents-pumpkin-focus",
  "Accents/Pumpkin/on-color": "--accents-pumpkin-on-color",
  "Accents/Pumpkin/on-color-hover": "--accents-pumpkin-on-color-hover",
  "Border/alert/default": "--border-alert-default",
  "Border/alert/default-hover": "--border-alert-default-hover",
  "Border/alert/default-subtle": "--border-alert-default-subtle",
  "Border/alert/default-subtle-hover": "--border-alert-default-subtle-hover",
  "Border/alert/focus": "--border-alert-focus",
  "Border/bronze/default": "--border-bronze-default",
  "Border/bronze/default-hover": "--border-bronze-default-hover",
  "Border/bronze/default-subtle": "--border-bronze-default-subtle",
  "Border/bronze/default-subtle-hover": "--border-bronze-default-subtle-hover",
  "Border/bronze/focus": "--border-bronze-focus",
  "Border/default": "--border-default",
  "Border/disabled/primary": "--border-disabled-primary",
  "Border/disabled/secondary": "--border-disabled-secondary",
  "Border/general/default": "--border-general-default",
  "Border/general/default-secondary": "--border-general-default-secondary",
  "Border/general/default-tertiary": "--border-general-default-tertiary",
  "Border/general/page": "--border-general-page",
  "Border/general/page-secondary": "--border-general-page-secondary",
  "Border/gold/default": "--border-gold-default",
  "Border/gold/default-hover": "--border-gold-default-hover",
  "Border/gold/default-subtle": "--border-gold-default-subtle",
  "Border/gold/default-subtle-hover": "--border-gold-default-subtle-hover",
  "Border/gold/focus": "--border-gold-focus",
  "Border/informative/default": "--border-informative-default",
  "Border/informative/default-hover": "--border-informative-default-hover",
  "Border/informative/default-subtle": "--border-informative-default-subtle",
  "Border/informative/default-subtle-hover": "--border-informative-default-subtle-hover",
  "Border/informative/focus": "--border-informative-focus",
  "Border/on-color": "--border-on-color",
  "Border/primary/default": "--border-primary-default",
  "Border/primary/default-hover": "--border-primary-default-hover",
  "Border/primary/default-subtle": "--border-primary-default-subtle",
  "Border/primary/default-subtle-hover": "--border-primary-default-subtle-hover",
  "Border/primary/focus": "--border-primary-focus",
  "Border/secondary/default": "--border-secondary-default",
  "Border/secondary/default-hover": "--border-secondary-default-hover",
  "Border/secondary/default-subtle": "--border-secondary-default-subtle",
  "Border/secondary/default-subtle-hover": "--border-secondary-default-subtle-hover",
  "Border/secondary/focus": "--border-secondary-focus",
  "Border/silver/default": "--border-silver-default",
  "Border/silver/default-hover": "--border-silver-default-hover",
  "Border/silver/default-subtle": "--border-silver-default-subtle",
  "Border/silver/default-subtle-hover": "--border-silver-default-subtle-hover",
  "Border/silver/focus": "--border-silver-focus",
  "Border/success/default": "--border-success-default",
  "Border/success/default-hover": "--border-success-default-hover",
  "Border/success/default-subtle": "--border-success-default-subtle",
  "Border/success/default-subtle-hover": "--border-success-default-subtle-hover",
  "Border/success/focus": "--border-success-focus",
  "Border/tertiary/default": "--border-tertiary-default",
  "Border/tertiary/default-hover": "--border-tertiary-default-hover",
  "Border/tertiary/default-subtle": "--border-tertiary-default-subtle",
  "Border/tertiary/default-subtle-hover": "--border-tertiary-default-subtle-hover",
  "Border/tertiary/focus": "--border-tertiary-focus",
  "Border/warning/default": "--border-warning-default",
  "Border/warning/default-hover": "--border-warning-default-hover",
  "Border/warning/default-subtle": "--border-warning-default-subtle",
  "Border/warning/default-subtle-hover": "--border-warning-default-subtle-hover",
  "Border/warning/focus": "--border-warning-focus",
  "Border Width/lg": "--border-width-lg",
  "Border Width/m": "--border-width-m",
  "Border Width/none": "--border-width-none",
  "Border Width/s": "--border-width-s",
  "Border Width/xs": "--border-width-xs",
  "Icon/alert/default": "--icon-alert-default",
  "Icon/alert/default-hover": "--icon-alert-default-hover",
  "Icon/alert/focus": "--icon-alert-focus",
  "Icon/alert/on-color": "--icon-alert-on-color",
  "Icon/alert/on-color-hover": "--icon-alert-on-color-hover",
  "Icon/default/default": "--icon-default-default",
  "Icon/disabled/default": "--icon-disabled-default",
  "Icon/disabled/on-color": "--icon-disabled-on-color",
  "Icon/disabled/on-icon": "--icon-disabled-on-icon",
  "Icon/grayscale/ramp-1": "--icon-grayscale-ramp-1",
  "Icon/grayscale/ramp-2": "--icon-grayscale-ramp-2",
  "Icon/grayscale/ramp-3": "--icon-grayscale-ramp-3",
  "Icon/grayscale/ramp-4": "--icon-grayscale-ramp-4",
  "Icon/grayscale/ramp-5": "--icon-grayscale-ramp-5",
  "Icon/informative/default": "--icon-informative-default",
  "Icon/informative/default-hover": "--icon-informative-default-hover",
  "Icon/informative/focus": "--icon-informative-focus",
  "Icon/informative/on-color": "--icon-informative-on-color",
  "Icon/informative/on-color-hover": "--icon-informative-on-color-hover",
  "Icon/primary/default": "--icon-primary-default",
  "Icon/primary/default-hover": "--icon-primary-default-hover",
  "Icon/primary/focus": "--icon-primary-focus",
  "Icon/primary/on-color": "--icon-primary-on-color",
  "Icon/primary/on-color-hover": "--icon-primary-on-color-hover",
  "Icon/secondary/default": "--icon-secondary-default",
  "Icon/secondary/default-hover": "--icon-secondary-default-hover",
  "Icon/secondary/focus": "--icon-secondary-focus",
  "Icon/secondary/on-color": "--icon-secondary-on-color",
  "Icon/secondary/on-color-hover": "--icon-secondary-on-color-hover",
  "Icon/success/default": "--icon-success-default",
  "Icon/success/default-hover": "--icon-success-default-hover",
  "Icon/success/focus": "--icon-success-focus",
  "Icon/success/on-color": "--icon-success-on-color",
  "Icon/success/on-color-hover": "--icon-success-on-color-hover",
  "Icon/tertiary/default": "--icon-tertiary-default",
  "Icon/tertiary/default-hover": "--icon-tertiary-default-hover",
  "Icon/tertiary/focus": "--icon-tertiary-focus",
  "Icon/tertiary/on-color": "--icon-tertiary-on-color",
  "Icon/tertiary/on-color-hover": "--icon-tertiary-on-color-hover",
  "Icon/warning/default": "--icon-warning-default",
  "Icon/warning/default-hover": "--icon-warning-default-hover",
  "Icon/warning/focus": "--icon-warning-focus",
  "Icon/warning/on-color": "--icon-warning-on-color",
  "Icon/warning/on-color-hover": "--icon-warning-on-color-hover",
  "Radius/2xl": "--radius-2xl",
  "Radius/3xl": "--radius-3xl",
  "Radius/4xl": "--radius-4xl",
  "Radius/full": "--radius-full",
  "Radius/lg": "--radius-lg",
  "Radius/md": "--radius-md",
  "Radius/none": "--radius-none",
  "Radius/pill": "--radius-pill",
  "Radius/sm": "--radius-sm",
  "Radius/xl": "--radius-xl",
  "Radius/xs": "--radius-xs",
  "Spacing/component/2xl": "--spacing-component-2xl",
  "Spacing/component/2xs": "--spacing-component-2xs",
  "Spacing/component/3xl": "--spacing-component-3xl",
  "Spacing/component/3xs": "--spacing-component-3xs",
  "Spacing/component/lg": "--spacing-component-lg",
  "Spacing/component/md": "--spacing-component-md",
  "Spacing/component/none": "--spacing-component-none",
  "Spacing/component/sm": "--spacing-component-sm",
  "Spacing/component/xl": "--spacing-component-xl",
  "Spacing/component/xs": "--spacing-component-xs",
  "Spacing/layout/lg": "--spacing-layout-lg",
  "Spacing/layout/md": "--spacing-layout-md",
  "Spacing/layout/sm": "--spacing-layout-sm",
  "Spacing/layout/xl": "--spacing-layout-xl",
  "Status/coins/default": "--status-coins-default",
  "Status/coins/focus": "--status-coins-focus",
  "Status/coins/on color": "--status-coins-on-color",
  "Status/lives/default": "--status-lives-default",
  "Status/lives/focus": "--status-lives-focus",
  "Status/lives/on color": "--status-lives-on-color",
  "Status/ruby/default": "--status-ruby-default",
  "Status/ruby/focus": "--status-ruby-focus",
  "Status/ruby/on color": "--status-ruby-on-color",
  "Status/score/default": "--status-score-default",
  "Status/score/focus": "--status-score-focus",
  "Status/score/on color": "--status-score-on-color",
  "Status/streak/default": "--status-streak-default",
  "Status/streak/focus": "--status-streak-focus",
  "Status/streak/on color": "--status-streak-on-color",
  "Subjects/account/default": "--subjects-account-default",
  "Subjects/account/default-hover": "--subjects-account-default-hover",
  "Subjects/account/default-subtle": "--subjects-account-default-subtle",
  "Subjects/account/default-subtle-hover": "--subjects-account-default-subtle-hover",
  "Subjects/account/focus": "--subjects-account-focus",
  "Subjects/add-math/default": "--subjects-add-math-default",
  "Subjects/add-math/default-hover": "--subjects-add-math-default-hover",
  "Subjects/add-math/default-subtle": "--subjects-add-math-default-subtle",
  "Subjects/add-math/default-subtle-hover": "--subjects-add-math-default-subtle-hover",
  "Subjects/add-math/focus": "--subjects-add-math-focus",
  "Subjects/b-melayu/default": "--subjects-b-melayu-default",
  "Subjects/b-melayu/default-hover": "--subjects-b-melayu-default-hover",
  "Subjects/b-melayu/default-subtle": "--subjects-b-melayu-default-subtle",
  "Subjects/b-melayu/default-subtle-hover": "--subjects-b-melayu-default-subtle-hover",
  "Subjects/b-melayu/focus": "--subjects-b-melayu-focus",
  "Subjects/biology/default": "--subjects-biology-default",
  "Subjects/biology/default-hover": "--subjects-biology-default-hover",
  "Subjects/biology/default-subtle": "--subjects-biology-default-subtle",
  "Subjects/biology/default-subtle-hover": "--subjects-biology-default-subtle-hover",
  "Subjects/biology/focus": "--subjects-biology-focus",
  "Subjects/business/default": "--subjects-business-default",
  "Subjects/business/default-hover": "--subjects-business-default-hover",
  "Subjects/business/default-subtle": "--subjects-business-default-subtle",
  "Subjects/business/default-subtle-hover": "--subjects-business-default-subtle-hover",
  "Subjects/business/focus": "--subjects-business-focus",
  "Subjects/chemistry/default": "--subjects-chemistry-default",
  "Subjects/chemistry/default-hover": "--subjects-chemistry-default-hover",
  "Subjects/chemistry/default-subtle": "--subjects-chemistry-default-subtle",
  "Subjects/chemistry/default-subtle-hover": "--subjects-chemistry-default-subtle-hover",
  "Subjects/chemistry/focus": "--subjects-chemistry-focus",
  "Subjects/chi-lang/default": "--subjects-chi-lang-default",
  "Subjects/chi-lang/default-hover": "--subjects-chi-lang-default-hover",
  "Subjects/chi-lang/default-subtle": "--subjects-chi-lang-default-subtle",
  "Subjects/chi-lang/default-subtle-hover": "--subjects-chi-lang-default-subtle-hover",
  "Subjects/chi-lang/focus": "--subjects-chi-lang-focus",
  "Subjects/comp-science/default": "--subjects-comp-science-default",
  "Subjects/comp-science/default-hover": "--subjects-comp-science-default-hover",
  "Subjects/comp-science/default-subtle": "--subjects-comp-science-default-subtle",
  "Subjects/comp-science/default-subtle-hover": "--subjects-comp-science-default-subtle-hover",
  "Subjects/comp-science/focus": "--subjects-comp-science-focus",
  "Subjects/economy/default": "--subjects-economy-default",
  "Subjects/economy/default-hover": "--subjects-economy-default-hover",
  "Subjects/economy/default-subtle": "--subjects-economy-default-subtle",
  "Subjects/economy/default-subtle-hover": "--subjects-economy-default-subtle-hover",
  "Subjects/economy/focus": "--subjects-economy-focus",
  "Subjects/english/default": "--subjects-english-default",
  "Subjects/english/default-hover": "--subjects-english-default-hover",
  "Subjects/english/default-subtle": "--subjects-english-default-subtle",
  "Subjects/english/default-subtle-hover": "--subjects-english-default-subtle-hover",
  "Subjects/english/focus": "--subjects-english-focus",
  "Subjects/geo/default": "--subjects-geo-default",
  "Subjects/geo/default-hover": "--subjects-geo-default-hover",
  "Subjects/geo/default-subtle": "--subjects-geo-default-subtle",
  "Subjects/geo/default-subtle-hover": "--subjects-geo-default-subtle-hover",
  "Subjects/geo/focus": "--subjects-geo-focus",
  "Subjects/history/default": "--subjects-history-default",
  "Subjects/history/default-hover": "--subjects-history-default-hover",
  "Subjects/history/default-subtle": "--subjects-history-default-subtle",
  "Subjects/history/default-subtle-hover": "--subjects-history-default-subtle-hover",
  "Subjects/history/focus": "--subjects-history-focus",
  "Subjects/islamic/default": "--subjects-islamic-default",
  "Subjects/islamic/default-hover": "--subjects-islamic-default-hover",
  "Subjects/islamic/default-subtle": "--subjects-islamic-default-subtle",
  "Subjects/islamic/default-subtle-hover": "--subjects-islamic-default-subtle-hover",
  "Subjects/islamic/focus": "--subjects-islamic-focus",
  "Subjects/kafa/default": "--subjects-kafa-default",
  "Subjects/kafa/default-hover": "--subjects-kafa-default-hover",
  "Subjects/kafa/default-subtle": "--subjects-kafa-default-subtle",
  "Subjects/kafa/default-subtle-hover": "--subjects-kafa-default-subtle-hover",
  "Subjects/kafa/focus": "--subjects-kafa-focus",
  "Subjects/math/default": "--subjects-math-default",
  "Subjects/math/default-hover": "--subjects-math-default-hover",
  "Subjects/math/default-subtle": "--subjects-math-default-subtle",
  "Subjects/math/default-subtle-hover": "--subjects-math-default-subtle-hover",
  "Subjects/math/focus": "--subjects-math-focus",
  "Subjects/moral/default": "--subjects-moral-default",
  "Subjects/moral/default-hover": "--subjects-moral-default-hover",
  "Subjects/moral/default-subtle": "--subjects-moral-default-subtle",
  "Subjects/moral/default-subtle-hover": "--subjects-moral-default-subtle-hover",
  "Subjects/moral/focus": "--subjects-moral-focus",
  "Subjects/physics/default": "--subjects-physics-default",
  "Subjects/physics/default-hover": "--subjects-physics-default-hover",
  "Subjects/physics/default-subtle": "--subjects-physics-default-subtle",
  "Subjects/physics/default-subtle-hover": "--subjects-physics-default-subtle-hover",
  "Subjects/physics/focus": "--subjects-physics-focus",
  "Subjects/rbt/default": "--subjects-rbt-default",
  "Subjects/rbt/default-hover": "--subjects-rbt-default-hover",
  "Subjects/rbt/default-subtle": "--subjects-rbt-default-subtle",
  "Subjects/rbt/default-subtle-hover": "--subjects-rbt-default-subtle-hover",
  "Subjects/rbt/focus": "--subjects-rbt-focus",
  "Subjects/science/default": "--subjects-science-default",
  "Subjects/science/default-hover": "--subjects-science-default-hover",
  "Subjects/science/default-subtle": "--subjects-science-default-subtle",
  "Subjects/science/default-subtle-hover": "--subjects-science-default-subtle-hover",
  "Subjects/science/focus": "--subjects-science-focus",
  "Surface/alert/default": "--surface-alert-default",
  "Surface/alert/default-hover": "--surface-alert-default-hover",
  "Surface/alert/default-subtle": "--surface-alert-default-subtle",
  "Surface/alert/default-subtle-hover": "--surface-alert-default-subtle-hover",
  "Surface/alert/focus": "--surface-alert-focus",
  "Surface/bronze/default": "--surface-bronze-default",
  "Surface/bronze/default-hover": "--surface-bronze-default-hover",
  "Surface/bronze/default-subtle": "--surface-bronze-default-subtle",
  "Surface/bronze/default-subtle-hover": "--surface-bronze-default-subtle-hover",
  "Surface/bronze/focus": "--surface-bronze-focus",
  "Surface/disabled/on color": "--surface-disabled-on-color",
  "Surface/disabled/primary": "--surface-disabled-primary",
  "Surface/disabled/secondary": "--surface-disabled-secondary",
  "Surface/general/default": "--surface-general-default",
  "Surface/general/default-alpha": "--surface-general-default-alpha",
  "Surface/general/default-secondary": "--surface-general-default-secondary",
  "Surface/general/default-tertiary": "--surface-general-default-tertiary",
  "Surface/general/page": "--surface-general-page",
  "Surface/general/page-secondary": "--surface-general-page-secondary",
  "Surface/general/pandai-logo": "--surface-general-pandai-logo",
  "Surface/gold/default": "--surface-gold-default",
  "Surface/gold/default-hover": "--surface-gold-default-hover",
  "Surface/gold/default-subtle": "--surface-gold-default-subtle",
  "Surface/gold/default-subtle-hover": "--surface-gold-default-subtle-hover",
  "Surface/gold/focus": "--surface-gold-focus",
  "Surface/informative/default": "--surface-informative-default",
  "Surface/informative/default-hover": "--surface-informative-default-hover",
  "Surface/informative/default-subtle": "--surface-informative-default-subtle",
  "Surface/informative/default-subtle-hover": "--surface-informative-default-subtle-hover",
  "Surface/informative/focus": "--surface-informative-focus",
  "Surface/menu-item/hover": "--surface-menu-item-hover",
  "Surface/primary/default": "--surface-primary-default",
  "Surface/primary/default-hover": "--surface-primary-default-hover",
  "Surface/primary/default-subtle": "--surface-primary-default-subtle",
  "Surface/primary/default-subtle-hover": "--surface-primary-default-subtle-hover",
  "Surface/primary/focus": "--surface-primary-focus",
  "Surface/secondary/default": "--surface-secondary-default",
  "Surface/secondary/default-btn": "--surface-secondary-default-btn",
  "Surface/secondary/default-hover": "--surface-secondary-default-hover",
  "Surface/secondary/default-subtle": "--surface-secondary-default-subtle",
  "Surface/secondary/default-subtle-hover": "--surface-secondary-default-subtle-hover",
  "Surface/secondary/focus": "--surface-secondary-focus",
  "Surface/silver/default": "--surface-silver-default",
  "Surface/silver/default-hover": "--surface-silver-default-hover",
  "Surface/silver/default-subtle": "--surface-silver-default-subtle",
  "Surface/silver/default-subtle-hover": "--surface-silver-default-subtle-hover",
  "Surface/silver/focus": "--surface-silver-focus",
  "Surface/success/default": "--surface-success-default",
  "Surface/success/default-hover": "--surface-success-default-hover",
  "Surface/success/default-subtle": "--surface-success-default-subtle",
  "Surface/success/default-subtle-hover": "--surface-success-default-subtle-hover",
  "Surface/success/focus": "--surface-success-focus",
  "Surface/tertiary/default": "--surface-tertiary-default",
  "Surface/tertiary/default-hover": "--surface-tertiary-default-hover",
  "Surface/tertiary/default-subtle": "--surface-tertiary-default-subtle",
  "Surface/tertiary/default-subtle-hover": "--surface-tertiary-default-subtle-hover",
  "Surface/tertiary/focus": "--surface-tertiary-focus",
  "Surface/warning/default": "--surface-warning-default",
  "Surface/warning/default-hover": "--surface-warning-default-hover",
  "Surface/warning/default-subtle": "--surface-warning-default-subtle",
  "Surface/warning/default-subtle-hover": "--surface-warning-default-subtle-hover",
  "Surface/warning/focus": "--surface-warning-focus",
  "Text/alert/default": "--text-alert-default",
  "Text/alert/default-hover": "--text-alert-default-hover",
  "Text/alert/on-color": "--text-alert-on-color",
  "Text/alert/on-color-hover": "--text-alert-on-color-hover",
  "Text/default/body": "--text-default-body",
  "Text/default/caption": "--text-default-caption",
  "Text/default/heading": "--text-default-heading",
  "Text/default/placeholder": "--text-default-placeholder",
  "Text/disabled/default": "--text-disabled-default",
  "Text/disabled/on-color": "--text-disabled-on-color",
  "Text/informative/default": "--text-informative-default",
  "Text/informative/default-hover": "--text-informative-default-hover",
  "Text/informative/on-color": "--text-informative-on-color",
  "Text/informative/on-color-hover": "--text-informative-on-color-hover",
  "Text/on-color/body": "--text-on-color-body",
  "Text/on-color/caption": "--text-on-color-caption",
  "Text/on-color/heading": "--text-on-color-heading",
  "Text/on-color/placeholder": "--text-on-color-placeholder",
  "Text/primary/default": "--text-primary-default",
  "Text/primary/default-hover": "--text-primary-default-hover",
  "Text/primary/focus": "--text-primary-focus",
  "Text/primary/on-color": "--text-primary-on-color",
  "Text/primary/on-color-hover": "--text-primary-on-color-hover",
  "Text/secondary/default": "--text-secondary-default",
  "Text/secondary/default-hover": "--text-secondary-default-hover",
  "Text/secondary/focus": "--text-secondary-focus",
  "Text/secondary/on-color": "--text-secondary-on-color",
  "Text/secondary/on-color-hover": "--text-secondary-on-color-hover",
  "Text/success/default": "--text-success-default",
  "Text/success/default-hover": "--text-success-default-hover",
  "Text/success/on-color": "--text-success-on-color",
  "Text/success/on-color-hover": "--text-success-on-color-hover",
  "Text/tertiary/default": "--text-tertiary-default",
  "Text/tertiary/default-hover": "--text-tertiary-default-hover",
  "Text/tertiary/focus": "--text-tertiary-focus",
  "Text/tertiary/on-color": "--text-tertiary-on-color",
  "Text/tertiary/on-color-hover": "--text-tertiary-on-color-hover",
  "Text/warning/default": "--text-warning-default",
  "Text/warning/default-hover": "--text-warning-default-hover",
  "Text/warning/on-color": "--text-warning-on-color",
  "Text/warning/on-color-hover": "--text-warning-on-color-hover",
} as const;

export type TokenPath = keyof typeof TOKEN_VARS;

/**
 * Literal values, keyed by CSS variable name.
 *
 * Canvas cannot consume a var() reference; it needs a real value, read at
 * runtime from the stylesheet. This map is the fallback for when that read
 * returns nothing - an unmounted node, or a headless render. It exists so that
 * no component ever writes a colour literal of its own, which check:ds forbids.
 */
export const VAR_VALUES: Record<string, string> = {
  "--accents-azure-default": "#30a9e5",
  "--accents-azure-default-hover": "#2a86b3",
  "--accents-azure-focus": "#2a86b3",
  "--accents-azure-on-color": "#ffffff",
  "--accents-azure-on-color-hover": "#d5edfb",
  "--accents-butter-default": "#ffffc9",
  "--accents-butter-default-hover": "#cccca1",
  "--accents-butter-focus": "#cccca1",
  "--accents-butter-on-color": "#ffffff",
  "--accents-butter-on-color-hover": "#fffff4",
  "--accents-minion-default": "#fff200",
  "--accents-minion-default-hover": "#ccc200",
  "--accents-minion-focus": "#ccc200",
  "--accents-minion-on-color": "#ffffff",
  "--accents-minion-on-color-hover": "#fffccc",
  "--accents-pumpkin-default": "#f2b839",
  "--accents-pumpkin-default-hover": "#c2932e",
  "--accents-pumpkin-focus": "#c2932e",
  "--accents-pumpkin-on-color": "#ffffff",
  "--accents-pumpkin-on-color-hover": "#fcf1d7",
  "--border-alert-default": "#ff9f43",
  "--border-alert-default-hover": "#ffcea0",
  "--border-alert-default-subtle": "#fff6ed",
  "--border-alert-default-subtle-hover": "#ffe3c7",
  "--border-alert-focus": "#b26f2f",
  "--border-bronze-default": "#d47d62",
  "--border-bronze-default-hover": "#e5b1a1",
  "--border-bronze-default-subtle": "#f6e5e0",
  "--border-bronze-default-subtle-hover": "#eecbc0",
  "--border-bronze-focus": "#aa644e",
  "--border-default": "#00cc85",
  "--border-disabled-primary": "#bfbfbf",
  "--border-disabled-secondary": "#bfbfbf",
  "--border-general-default": "#bfbfbf",
  "--border-general-default-secondary": "#ffffff",
  "--border-general-default-tertiary": "#e5e5e5",
  "--border-general-page": "#ffffff",
  "--border-general-page-secondary": "#e5e5e5",
  "--border-gold-default": "#fabb0a",
  "--border-gold-default-hover": "#fcd66c",
  "--border-gold-default-subtle": "#fef1ce",
  "--border-gold-default-subtle-hover": "#fde49d",
  "--border-gold-focus": "#967006",
  "--border-informative-default": "#00a2e8",
  "--border-informative-default-hover": "#7fd0f3",
  "--border-informative-default-subtle": "#e6f6fd",
  "--border-informative-default-subtle-hover": "#b3e4f9",
  "--border-informative-focus": "#0071a2",
  "--border-on-color": "#ffffff",
  "--border-primary-default": "#00cc85",
  "--border-primary-default-hover": "#66e0b6",
  "--border-primary-default-subtle": "#d9f7ed",
  "--border-primary-default-subtle-hover": "#99ebce",
  "--border-primary-focus": "#00a36a",
  "--border-secondary-default": "#b5f291",
  "--border-secondary-default-hover": "#baf3b9",
  "--border-secondary-default-subtle": "#e8fbe8",
  "--border-secondary-default-subtle-hover": "#baf3b9",
  "--border-secondary-focus": "#70bc6f",
  "--border-silver-default": "#878dbb",
  "--border-silver-default-hover": "#b7bbd6",
  "--border-silver-default-subtle": "#e7e8f1",
  "--border-silver-default-subtle-hover": "#cfd1e4",
  "--border-silver-focus": "#6c7196",
  "--border-success-default": "#18c964",
  "--border-success-default-hover": "#74dfa2",
  "--border-success-default-subtle": "#d1f4e0",
  "--border-success-default-subtle-hover": "#a3e9c1",
  "--border-success-focus": "#13a150",
  "--border-tertiary-default": "#00564c",
  "--border-tertiary-default-hover": "#669a94",
  "--border-tertiary-default-subtle": "#ccdddb",
  "--border-tertiary-default-subtle-hover": "#99bbb7",
  "--border-tertiary-focus": "#00453d",
  "--border-warning-default": "#ff4c51",
  "--border-warning-default-hover": "#ffa5a7",
  "--border-warning-default-subtle": "#ffeeee",
  "--border-warning-default-subtle-hover": "#ffcacb",
  "--border-warning-focus": "#b23539",
  "--border-width-lg": "8px",
  "--border-width-m": "4px",
  "--border-width-none": "0px",
  "--border-width-s": "2px",
  "--border-width-xs": "1px",
  "--icon-alert-default": "#ff9f43",
  "--icon-alert-default-hover": "#ffcea0",
  "--icon-alert-focus": "#b26f2f",
  "--icon-alert-on-color": "#ffffff",
  "--icon-alert-on-color-hover": "#ffffff",
  "--icon-default-default": "#a6a6a6",
  "--icon-disabled-default": "#bfbfbf",
  "--icon-disabled-on-color": "#f2f2f2",
  "--icon-disabled-on-icon": "#f2f2f2",
  "--icon-grayscale-ramp-1": "#8f929a",
  "--icon-grayscale-ramp-2": "#b4b7bb",
  "--icon-grayscale-ramp-3": "#dadbdd",
  "--icon-grayscale-ramp-4": "#dadbdd",
  "--icon-grayscale-ramp-5": "#f4f5f5",
  "--icon-informative-default": "#00a2e8",
  "--icon-informative-default-hover": "#7fd0f3",
  "--icon-informative-focus": "#0071a2",
  "--icon-informative-on-color": "#ffffff",
  "--icon-informative-on-color-hover": "#ffffff",
  "--icon-primary-default": "#00cc85",
  "--icon-primary-default-hover": "#00a36a",
  "--icon-primary-focus": "#00a36a",
  "--icon-primary-on-color": "#e1f9ea",
  "--icon-primary-on-color-hover": "#d9f7ed",
  "--icon-secondary-default": "#b5f291",
  "--icon-secondary-default-hover": "#f6fef6",
  "--icon-secondary-focus": "#70bc6f",
  "--icon-secondary-on-color": "#e8fbe8",
  "--icon-secondary-on-color-hover": "#d1f7d1",
  "--icon-success-default": "#18c964",
  "--icon-success-default-hover": "#74dfa2",
  "--icon-success-focus": "#13a150",
  "--icon-success-on-color": "#ffffff",
  "--icon-success-on-color-hover": "#ffffff",
  "--icon-tertiary-default": "#00564c",
  "--icon-tertiary-default-hover": "#00453d",
  "--icon-tertiary-focus": "#00453d",
  "--icon-tertiary-on-color": "#ffffff",
  "--icon-tertiary-on-color-hover": "#ccdddb",
  "--icon-warning-default": "#ff4c51",
  "--icon-warning-default-hover": "#ffa5a7",
  "--icon-warning-focus": "#b23539",
  "--icon-warning-on-color": "#ffffff",
  "--icon-warning-on-color-hover": "#ffffff",
  "--radius-2xl": "18px",
  "--radius-3xl": "24px",
  "--radius-4xl": "54px",
  "--radius-full": "60px",
  "--radius-lg": "12px",
  "--radius-md": "8px",
  "--radius-none": "0px",
  "--radius-pill": "999px",
  "--radius-sm": "4px",
  "--radius-xl": "16px",
  "--radius-xs": "2px",
  "--spacing-component-2xl": "28px",
  "--spacing-component-2xs": "4px",
  "--spacing-component-3xl": "60px",
  "--spacing-component-3xs": "2px",
  "--spacing-component-lg": "20px",
  "--spacing-component-md": "16px",
  "--spacing-component-none": "0px",
  "--spacing-component-sm": "12px",
  "--spacing-component-xl": "24px",
  "--spacing-component-xs": "8px",
  "--spacing-layout-lg": "60px",
  "--spacing-layout-md": "24px",
  "--spacing-layout-sm": "16px",
  "--spacing-layout-xl": "108px",
  "--status-coins-default": "#fece00",
  "--status-coins-focus": "#cba500",
  "--status-coins-on-color": "#ffffff",
  "--status-lives-default": "#ff5c98",
  "--status-lives-focus": "#cc4a7a",
  "--status-lives-on-color": "#ffffff",
  "--status-ruby-default": "#ff4c51",
  "--status-ruby-focus": "#b23539",
  "--status-ruby-on-color": "#ffffff",
  "--status-score-default": "#00cc85",
  "--status-score-focus": "#00a36a",
  "--status-score-on-color": "#ffffff",
  "--status-streak-default": "#7367f0",
  "--status-streak-focus": "#5c52c0",
  "--status-streak-on-color": "#ffffff",
  "--subjects-account-default": "#0072ca",
  "--subjects-account-default-hover": "#005ba2",
  "--subjects-account-default-subtle": "#eef5fc",
  "--subjects-account-default-subtle-hover": "#99c7ea",
  "--subjects-account-focus": "#004479",
  "--subjects-add-math-default": "#283589",
  "--subjects-add-math-default-hover": "#202a6e",
  "--subjects-add-math-default-subtle": "#f2f3f8",
  "--subjects-add-math-default-subtle-hover": "#a9aed0",
  "--subjects-add-math-focus": "#182052",
  "--subjects-b-melayu-default": "#4d77ff",
  "--subjects-b-melayu-default-hover": "#3e5fcc",
  "--subjects-b-melayu-default-subtle": "#ebf1ff",
  "--subjects-b-melayu-default-subtle-hover": "#b8c9ff",
  "--subjects-b-melayu-focus": "#2e4799",
  "--subjects-biology-default": "#8431d8",
  "--subjects-biology-default-hover": "#6a27ad",
  "--subjects-biology-default-subtle": "#f5eefc",
  "--subjects-biology-default-subtle-hover": "#ceadef",
  "--subjects-biology-focus": "#4f1d82",
  "--subjects-business-default": "#efb42b",
  "--subjects-business-default-hover": "#bf9022",
  "--subjects-business-default-subtle": "#fef8ea",
  "--subjects-business-default-subtle-hover": "#f9e1aa",
  "--subjects-business-focus": "#8f6c1a",
  "--subjects-chemistry-default": "#e20082",
  "--subjects-chemistry-default-hover": "#b50068",
  "--subjects-chemistry-default-subtle": "#fdedf6",
  "--subjects-chemistry-default-subtle-hover": "#ed99c6",
  "--subjects-chemistry-focus": "#88004e",
  "--subjects-chi-lang-default": "#f94848",
  "--subjects-chi-lang-default-hover": "#c73a3a",
  "--subjects-chi-lang-default-subtle": "#ffeded",
  "--subjects-chi-lang-default-subtle-hover": "#fdb6b6",
  "--subjects-chi-lang-focus": "#952b2b",
  "--subjects-comp-science-default": "#d10070",
  "--subjects-comp-science-default-hover": "#a7005a",
  "--subjects-comp-science-default-subtle": "#fcedf5",
  "--subjects-comp-science-default-subtle-hover": "#ed99c6",
  "--subjects-comp-science-focus": "#7d0043",
  "--subjects-economy-default": "#ff5733",
  "--subjects-economy-default-hover": "#cc4629",
  "--subjects-economy-default-subtle": "#ffeeeb",
  "--subjects-economy-default-subtle-hover": "#ffbcad",
  "--subjects-economy-focus": "#99341f",
  "--subjects-english-default": "#ff4d56",
  "--subjects-english-default-hover": "#cc3e45",
  "--subjects-english-default-subtle": "#ffedee",
  "--subjects-english-default-subtle-hover": "#ffb8bb",
  "--subjects-english-focus": "#992e34",
  "--subjects-geo-default": "#77d836",
  "--subjects-geo-default-hover": "#5fad2b",
  "--subjects-geo-default-subtle": "#f4fcee",
  "--subjects-geo-default-subtle-hover": "#c9efaf",
  "--subjects-geo-focus": "#478220",
  "--subjects-history-default": "#a97c50",
  "--subjects-history-default-hover": "#876340",
  "--subjects-history-default-subtle": "#f8f4f1",
  "--subjects-history-default-subtle-hover": "#ddcbb9",
  "--subjects-history-focus": "#654a30",
  "--subjects-islamic-default": "#de4d7f",
  "--subjects-islamic-default-hover": "#b23e66",
  "--subjects-islamic-default-subtle": "#fcedf2",
  "--subjects-islamic-default-subtle-hover": "#f2b8cc",
  "--subjects-islamic-focus": "#852e4c",
  "--subjects-kafa-default": "#8ae3a9",
  "--subjects-kafa-default-hover": "#6eb687",
  "--subjects-kafa-default-subtle": "#effbf3",
  "--subjects-kafa-default-subtle-hover": "#d0f4dd",
  "--subjects-kafa-focus": "#538865",
  "--subjects-math-default": "#42ac7b",
  "--subjects-math-default-hover": "#358a62",
  "--subjects-math-default-subtle": "#f1f9f5",
  "--subjects-math-default-subtle-hover": "#b3deca",
  "--subjects-math-focus": "#28674a",
  "--subjects-moral-default": "#0072ca",
  "--subjects-moral-default-hover": "#005ba2",
  "--subjects-moral-default-subtle": "#eef5fc",
  "--subjects-moral-default-subtle-hover": "#99c7ea",
  "--subjects-moral-focus": "#004479",
  "--subjects-physics-default": "#27a0d7",
  "--subjects-physics-default-hover": "#1f80ac",
  "--subjects-physics-default-subtle": "#eef8fc",
  "--subjects-physics-default-subtle-hover": "#a9d9ef",
  "--subjects-physics-focus": "#176081",
  "--subjects-rbt-default": "#353535",
  "--subjects-rbt-default-hover": "#2a2a2a",
  "--subjects-rbt-default-subtle": "#f5f5f5",
  "--subjects-rbt-default-subtle-hover": "#aeaeae",
  "--subjects-rbt-focus": "#202020",
  "--subjects-science-default": "#ffd641",
  "--subjects-science-default-hover": "#ccab34",
  "--subjects-science-default-subtle": "#fffbec",
  "--subjects-science-default-subtle-hover": "#ffefb3",
  "--subjects-science-focus": "#998027",
  "--surface-alert-default": "#ff9f43",
  "--surface-alert-default-hover": "#ffcea0",
  "--surface-alert-default-subtle": "#fff6ed",
  "--surface-alert-default-subtle-hover": "#ffe3c7",
  "--surface-alert-focus": "#b26f2f",
  "--surface-bronze-default": "#d47d62",
  "--surface-bronze-default-hover": "#aa644e",
  "--surface-bronze-default-subtle": "#f6e5e0",
  "--surface-bronze-default-subtle-hover": "#eecbc0",
  "--surface-bronze-focus": "#aa644e",
  "--surface-disabled-on-color": "#e5e5e5",
  "--surface-disabled-primary": "#f2f2f2",
  "--surface-disabled-secondary": "#f2f2f2",
  "--surface-general-default": "#ffffff",
  "--surface-general-default-alpha": "#ffffff80",
  "--surface-general-default-secondary": "#ffffff",
  "--surface-general-default-tertiary": "#ffffff",
  "--surface-general-page": "#ffffff",
  "--surface-general-page-secondary": "#e5e5e5",
  "--surface-general-pandai-logo": "#444a56",
  "--surface-gold-default": "#fabb0a",
  "--surface-gold-default-hover": "#c89608",
  "--surface-gold-default-subtle": "#fef1ce",
  "--surface-gold-default-subtle-hover": "#fde49d",
  "--surface-gold-focus": "#c89608",
  "--surface-informative-default": "#00a2e8",
  "--surface-informative-default-hover": "#7fd0f3",
  "--surface-informative-default-subtle": "#e6f6fd",
  "--surface-informative-default-subtle-hover": "#b3e4f9",
  "--surface-informative-focus": "#0071a2",
  "--surface-menu-item-hover": "#f6fef6",
  "--surface-primary-default": "#00cc85",
  "--surface-primary-default-hover": "#00a36a",
  "--surface-primary-default-subtle": "#e1f9ea",
  "--surface-primary-default-subtle-hover": "#99ebce",
  "--surface-primary-focus": "#00a36a",
  "--surface-secondary-default": "#b5f291",
  "--surface-secondary-default-btn": "#f6fef6",
  "--surface-secondary-default-hover": "#e8fbe8",
  "--surface-secondary-default-subtle": "#f6fef6",
  "--surface-secondary-default-subtle-hover": "#baf3b9",
  "--surface-secondary-focus": "#70bc6f",
  "--surface-silver-default": "#878dbb",
  "--surface-silver-default-hover": "#6c7196",
  "--surface-silver-default-subtle": "#e7e8f1",
  "--surface-silver-default-subtle-hover": "#cfd1e4",
  "--surface-silver-focus": "#6c7196",
  "--surface-success-default": "#18c964",
  "--surface-success-default-hover": "#74dfa2",
  "--surface-success-default-subtle": "#d1f4e0",
  "--surface-success-default-subtle-hover": "#a3e9c1",
  "--surface-success-focus": "#13a150",
  "--surface-tertiary-default": "#00564c",
  "--surface-tertiary-default-hover": "#00453d",
  "--surface-tertiary-default-subtle": "#e9f2f1",
  "--surface-tertiary-default-subtle-hover": "#99bbb7",
  "--surface-tertiary-focus": "#00453d",
  "--surface-warning-default": "#ff4c51",
  "--surface-warning-default-hover": "#ffa5a7",
  "--surface-warning-default-subtle": "#ffeeee",
  "--surface-warning-default-subtle-hover": "#ffcacb",
  "--surface-warning-focus": "#b23539",
  "--text-alert-default": "#ff9f43",
  "--text-alert-default-hover": "#ffcea0",
  "--text-alert-on-color": "#ffffff",
  "--text-alert-on-color-hover": "#ffffff",
  "--text-default-body": "#666666",
  "--text-default-caption": "#999999",
  "--text-default-heading": "#4d4d4d",
  "--text-default-placeholder": "#8c8c8c",
  "--text-disabled-default": "#bfbfbf",
  "--text-disabled-on-color": "#f2f2f2",
  "--text-informative-default": "#00a2e8",
  "--text-informative-default-hover": "#7fd0f3",
  "--text-informative-on-color": "#ffffff",
  "--text-informative-on-color-hover": "#ffffff",
  "--text-on-color-body": "#ffffff",
  "--text-on-color-caption": "#ffffff",
  "--text-on-color-heading": "#ffffff",
  "--text-on-color-placeholder": "#ffffff",
  "--text-primary-default": "#00cc85",
  "--text-primary-default-hover": "#00a36a",
  "--text-primary-focus": "#00a36a",
  "--text-primary-on-color": "#595959",
  "--text-primary-on-color-hover": "#e1f9ea",
  "--text-secondary-default": "#b5f291",
  "--text-secondary-default-hover": "#f6fef6",
  "--text-secondary-focus": "#548d53",
  "--text-secondary-on-color": "#e8fbe8",
  "--text-secondary-on-color-hover": "#d1f7d1",
  "--text-success-default": "#18c964",
  "--text-success-default-hover": "#74dfa2",
  "--text-success-on-color": "#ffffff",
  "--text-success-on-color-hover": "#ffffff",
  "--text-tertiary-default": "#00564c",
  "--text-tertiary-default-hover": "#00453d",
  "--text-tertiary-focus": "#00453d",
  "--text-tertiary-on-color": "#ffffff",
  "--text-tertiary-on-color-hover": "#e9f2f1",
  "--text-warning-default": "#ff4c51",
  "--text-warning-default-hover": "#ffa5a7",
  "--text-warning-on-color": "#ffffff",
  "--text-warning-on-color-hover": "#ffffff",
};

/** `var(--surface-primary-default)`, typo-proof. */
export function token(path: TokenPath): string {
  return `var(${TOKEN_VARS[path]})`;
}

/**
 * Subject identities from the DS. A game's accent is DERIVED from its subject
 * rather than chosen, so a Bahasa Melayu game wears the same blue it wears
 * everywhere else in Pandai - and the model never has to guess a colour.
 */
export const SUBJECT_KEYS = [
  "account",
  "add-math",
  "b-melayu",
  "biology",
  "business",
  "chemistry",
  "chi-lang",
  "comp-science",
  "economy",
  "english",
  "geo",
  "history",
  "islamic",
  "kafa",
  "math",
  "moral",
  "physics",
  "rbt",
  "science",
] as const;

export type SubjectKey = (typeof SUBJECT_KEYS)[number];

/**
 * Semantic accent families carrying the complete Surface ramp. Used only where
 * a game has no subject to derive from.
 */
export const ACCENT_FAMILIES = [
  "alert",
  "bronze",
  "gold",
  "informative",
  "primary",
  "secondary",
  "silver",
  "success",
  "tertiary",
  "warning",
] as const;

export type AccentFamily = (typeof ACCENT_FAMILIES)[number];

/** Game status colours - the DS already ships these. */
export const STATUS_KEYS = [
  "coins",
  "lives",
  "ruby",
  "score",
  "streak",
] as const;

export type StatusKey = (typeof STATUS_KEYS)[number];

export type Ramp = {
  default: string;
  hover: string;
  subtle: string;
  subtleHover: string;
  focus: string;
};

const ramp = (prefix: string): Ramp => ({
  default: `var(--${prefix}-default)`,
  hover: `var(--${prefix}-default-hover)`,
  subtle: `var(--${prefix}-default-subtle)`,
  subtleHover: `var(--${prefix}-default-subtle-hover)`,
  focus: `var(--${prefix}-focus)`,
});

export const subjectRamp = (s: SubjectKey): Ramp => ramp(`subjects-${s}`);
export const accentRamp = (a: AccentFamily): Ramp => ramp(`surface-${a}`);

/** Spacing scale. The house rule is 16 - see docs/DESIGN-SYSTEM-SYNC.md. */
export const SPACING = {
  "none": 0,
  "3xs": 2,
  "2xs": 4,
  "xs": 8,
  "sm": 12,
  "md": 16,
  "lg": 20,
  "xl": 24,
  "2xl": 28,
  "3xl": 60,
} as const;

export const RADIUS = {
  "none": 0,
  "xs": 2,
  "sm": 4,
  "md": 8,
  "lg": 12,
  "xl": 16,
  "2xl": 18,
  "3xl": 24,
  "4xl": 54,
  "full": 60,
  "pill": 999,
} as const;
